/**
 * Curated book-genome dataset powering the Book Map.
 *
 * Every book here is a real title with real bibliographic data. The `genes`
 * are editorial trope tags — a hand-curated reading of each book, not a
 * measurement Semantica computed from its text. Books ingested and analysed by
 * the backend join the map alongside these, with their genes derived from the
 * real theme profile.
 */

import { genreHex } from "@/components/ui/GenreTag";

export interface GenomeBook {
  id: string;
  title: string;
  author: string;
  year: number;
  pages: number;
  genre: string;
  genes: string[];
  blurb: string;
}

export interface BookGenomeData {
  /** Genre name -> hex swatch, resolved from the product palette. */
  genres: Record<string, string>;
  /** Gene slug -> human-readable meaning, shown on hover. */
  genes: Record<string, string>;
  books: GenomeBook[];
}

/**
 * Genres present in this dataset. Swatches are not defined here — they come
 * from the product-wide palette in GenreTag, so a book is the same colour on
 * the map as it is on its chip anywhere else.
 */
export const GENOME_GENRES = [
  "Fantasy",
  "Science Fiction",
  "Dystopian",
  "Classic",
  "Literary",
  "Thriller",
  "Horror",
  "Romance",
] as const;

export const GENRE_COLORS: Record<string, string> = Object.fromEntries(
  GENOME_GENRES.map((genre) => [genre, genreHex(genre)])
);

export const GENE_MEANINGS: Record<string, string> = {
  "epic-scope": "Sprawling, world-spanning stakes",
  "quest": "A journey toward a singular goal",
  "found-family": "A makeshift family forged by circumstance",
  "world-building": "Deep, immersive invented worlds",
  "good-vs-evil": "Clear moral poles in conflict",
  "war": "Conflict at the scale of nations",
  "coming-of-age": "A character grows into themselves",
  "adventure": "Momentum, peril, and discovery",
  "hopeful": "Light persists against the dark",
  "political-intrigue": "Power, scheming, and shifting alliances",
  "multiple-pov": "Story told through many eyes",
  "morally-grey": "Heroes and villains blur",
  "dark": "Bleak, heavy, unflinching tone",
  "magic-system": "Rule-bound, structured magic",
  "first-person": "Told intimately from inside one head",
  "character-driven": "Interiority over plot machinery",
  "chosen-one": "A destined protagonist",
  "heist": "An elaborate plan executed under pressure",
  "plot-twist": "A reveal that reframes everything",
  "mythology": "Rooted in myth and legend",
  "immortality": "Deathlessness and its costs",
  "atmospheric": "Mood and place as a character",
  "slow-burn-romance": "Love that simmers over time",
  "philosophical": "Big questions about meaning",
  "prophecy": "Fate foretold",
  "anti-hero": "A protagonist we shouldn't root for",
  "fast-paced": "Relentless forward propulsion",
  "ai": "Machine minds and their reach",
  "hard-sf": "Rigorous, science-forward speculation",
  "survival": "Staying alive against the odds",
  "problem-solving": "Ingenuity as the engine",
  "dystopia": "A society gone wrong",
  "satire": "Sharp social mockery",
  "literary": "Prose as the main event",
  "tragic": "Grief written into the bones",
  "historical": "Anchored in a real past",
  "redemption": "Earning back what was lost",
  "nonlinear": "Time folded out of order",
  "nature": "The wild as setting and force",
  "mystery": "A question that pulls you forward",
  "investigation": "The methodical hunt for truth",
  "isolated-setting": "Cut off, with nowhere to run",
  "ensemble": "A cast with no single lead",
  "unreliable-narrator": "A voice you can't quite trust",
  "psychological": "The mind as the battlefield",
  "gothic": "Decay, dread, and old houses",
  "epistolary": "Told in letters and documents",
  "science": "Discovery and its consequences",
  "class-struggle": "Wealth, status, and friction",
  "enemies-to-lovers": "Antagonism that turns to love",
  "revenge": "A wrong that demands an answer",
  "time-travel": "Slipping across time",
};

export const GENOME_BOOKS: GenomeBook[] = [
  {
    id: "lotr",
    title: "The Lord of the Rings",
    author: "J.R.R. Tolkien",
    year: 1954,
    pages: 1178,
    genre: "Fantasy",
    genes: ["epic-scope", "quest", "found-family", "world-building", "good-vs-evil", "war"],
    blurb: "A fellowship carries a world-ending ring across a continent on foot.",
  },
  {
    id: "hobbit",
    title: "The Hobbit",
    author: "J.R.R. Tolkien",
    year: 1937,
    pages: 310,
    genre: "Fantasy",
    genes: ["quest", "coming-of-age", "found-family", "adventure", "hopeful"],
    blurb: "A comfortable hobbit is dragged out his door and into a dragon's mountain.",
  },
  {
    id: "got",
    title: "A Game of Thrones",
    author: "George R.R. Martin",
    year: 1996,
    pages: 694,
    genre: "Fantasy",
    genes: ["epic-scope", "political-intrigue", "multiple-pov", "morally-grey", "war", "dark"],
    blurb: "Noble houses claw for a throne while a colder threat gathers in the north.",
  },
  {
    id: "notw",
    title: "The Name of the Wind",
    author: "Patrick Rothfuss",
    year: 2007,
    pages: 662,
    genre: "Fantasy",
    genes: ["magic-system", "coming-of-age", "first-person", "character-driven", "world-building"],
    blurb: "A legendary magician recounts, in his own words, how he was made and unmade.",
  },
  {
    id: "mistborn",
    title: "Mistborn",
    author: "Brandon Sanderson",
    year: 2006,
    pages: 541,
    genre: "Fantasy",
    genes: ["magic-system", "heist", "chosen-one", "world-building", "plot-twist"],
    blurb: "A street thief learns to burn metals for power and plots to topple a god-emperor.",
  },
  {
    id: "circe",
    title: "Circe",
    author: "Madeline Miller",
    year: 2018,
    pages: 393,
    genre: "Fantasy",
    genes: ["mythology", "first-person", "character-driven", "immortality", "coming-of-age"],
    blurb: "A minor goddess discovers witchcraft and exile on the long edge of myth.",
  },
  {
    id: "nightcircus",
    title: "The Night Circus",
    author: "Erin Morgenstern",
    year: 2011,
    pages: 387,
    genre: "Fantasy",
    genes: ["magic-system", "slow-burn-romance", "atmospheric", "world-building"],
    blurb: "Two magicians bound to a deadly contest fall in love inside a circus of impossibilities.",
  },
  {
    id: "dune",
    title: "Dune",
    author: "Frank Herbert",
    year: 1965,
    pages: 412,
    genre: "Science Fiction",
    genes: ["epic-scope", "political-intrigue", "chosen-one", "world-building", "philosophical", "prophecy"],
    blurb: "On a desert planet of spice and sandworms, a betrayed heir becomes a messiah.",
  },
  {
    id: "lefthand",
    title: "The Left Hand of Darkness",
    author: "Ursula K. Le Guin",
    year: 1969,
    pages: 304,
    genre: "Science Fiction",
    genes: ["philosophical", "political-intrigue", "world-building", "character-driven", "literary"],
    blurb: "An envoy navigates a frozen world whose people belong to no fixed gender.",
  },
  {
    id: "neuromancer",
    title: "Neuromancer",
    author: "William Gibson",
    year: 1984,
    pages: 271,
    genre: "Science Fiction",
    genes: ["dystopia", "anti-hero", "fast-paced", "dark", "ai"],
    blurb: "A burned-out hacker takes one last job jacked into a neon, corporate cyberspace.",
  },
  {
    id: "threebody",
    title: "The Three-Body Problem",
    author: "Liu Cixin",
    year: 2008,
    pages: 400,
    genre: "Science Fiction",
    genes: ["philosophical", "world-building", "plot-twist", "war", "hard-sf"],
    blurb: "A secret signal answered decades ago sets humanity on a collision course with the stars.",
  },
  {
    id: "phm",
    title: "Project Hail Mary",
    author: "Andy Weir",
    year: 2021,
    pages: 476,
    genre: "Science Fiction",
    genes: ["survival", "first-person", "fast-paced", "hopeful", "problem-solving"],
    blurb: "A man wakes alone on a spaceship with amnesia and the job of saving the sun.",
  },
  {
    id: "foundation",
    title: "Foundation",
    author: "Isaac Asimov",
    year: 1951,
    pages: 244,
    genre: "Science Fiction",
    genes: ["epic-scope", "political-intrigue", "philosophical", "world-building"],
    blurb: "A mathematician predicts the fall of empire and plants a seed to shorten the dark age.",
  },
  {
    id: "1984",
    title: "1984",
    author: "George Orwell",
    year: 1949,
    pages: 328,
    genre: "Dystopian",
    genes: ["dystopia", "political-intrigue", "dark", "tragic", "philosophical"],
    blurb: "A clerk in a surveillance state commits the crime of thinking for himself.",
  },
  {
    id: "bnw",
    title: "Brave New World",
    author: "Aldous Huxley",
    year: 1932,
    pages: 311,
    genre: "Dystopian",
    genes: ["dystopia", "philosophical", "satire", "dark"],
    blurb: "A society engineered for pleasure has quietly traded freedom for comfort.",
  },
  {
    id: "handmaid",
    title: "The Handmaid's Tale",
    author: "Margaret Atwood",
    year: 1985,
    pages: 311,
    genre: "Dystopian",
    genes: ["dystopia", "first-person", "dark", "political-intrigue", "literary"],
    blurb: "In a theocracy that prizes fertility above all, one woman records her survival.",
  },
  {
    id: "f451",
    title: "Fahrenheit 451",
    author: "Ray Bradbury",
    year: 1953,
    pages: 256,
    genre: "Dystopian",
    genes: ["dystopia", "philosophical", "dark", "hopeful"],
    blurb: "A fireman whose job is burning books begins, dangerously, to read them.",
  },
  {
    id: "theroad",
    title: "The Road",
    author: "Cormac McCarthy",
    year: 2006,
    pages: 287,
    genre: "Literary",
    genes: ["survival", "dark", "tragic", "character-driven", "literary"],
    blurb: "A father and son walk a dead, ashen country, carrying the fire between them.",
  },
  {
    id: "beloved",
    title: "Beloved",
    author: "Toni Morrison",
    year: 1987,
    pages: 324,
    genre: "Literary",
    genes: ["gothic", "tragic", "literary", "historical", "nonlinear"],
    blurb: "A formerly enslaved woman is haunted, literally, by the daughter she lost.",
  },
  {
    id: "kiterunner",
    title: "The Kite Runner",
    author: "Khaled Hosseini",
    year: 2003,
    pages: 371,
    genre: "Literary",
    genes: ["historical", "tragic", "coming-of-age", "redemption", "character-driven"],
    blurb: "A betrayal in childhood Kabul sends a man back, decades later, to make it right.",
  },
  {
    id: "crawdads",
    title: "Where the Crawdads Sing",
    author: "Delia Owens",
    year: 2018,
    pages: 384,
    genre: "Literary",
    genes: ["coming-of-age", "mystery", "character-driven", "slow-burn-romance", "nature"],
    blurb: "A girl raised alone in the marsh becomes the prime suspect in a small-town death.",
  },
  {
    id: "cap",
    title: "Crime and Punishment",
    author: "Fyodor Dostoevsky",
    year: 1866,
    pages: 671,
    genre: "Classic",
    genes: ["philosophical", "anti-hero", "psychological", "tragic", "dark"],
    blurb: "A poor student murders to prove a theory, then drowns in his own conscience.",
  },
  {
    id: "pride",
    title: "Pride and Prejudice",
    author: "Jane Austen",
    year: 1813,
    pages: 432,
    genre: "Classic",
    genes: ["enemies-to-lovers", "slow-burn-romance", "satire", "character-driven", "class-struggle"],
    blurb: "Two proud people misjudge each other thoroughly before they fall in love.",
  },
  {
    id: "janeeyre",
    title: "Jane Eyre",
    author: "Charlotte Brontë",
    year: 1847,
    pages: 532,
    genre: "Classic",
    genes: ["gothic", "slow-burn-romance", "first-person", "coming-of-age", "character-driven"],
    blurb: "A plain, fierce governess loves a brooding man with a secret locked upstairs.",
  },
  {
    id: "wuthering",
    title: "Wuthering Heights",
    author: "Emily Brontë",
    year: 1847,
    pages: 416,
    genre: "Classic",
    genes: ["gothic", "tragic", "dark", "revenge", "slow-burn-romance"],
    blurb: "A love so consuming it curses two families across the windswept moors.",
  },
  {
    id: "frankenstein",
    title: "Frankenstein",
    author: "Mary Shelley",
    year: 1818,
    pages: 280,
    genre: "Classic",
    genes: ["gothic", "philosophical", "tragic", "science", "morally-grey", "dark"],
    blurb: "A scientist gives life to a creature, then abandons it to its loneliness and rage.",
  },
  {
    id: "dracula",
    title: "Dracula",
    author: "Bram Stoker",
    year: 1897,
    pages: 418,
    genre: "Horror",
    genes: ["gothic", "immortality", "epistolary", "dark", "investigation"],
    blurb: "An ancient count moves to London, and a handful of hunters piece together the horror.",
  },
  {
    id: "shining",
    title: "The Shining",
    author: "Stephen King",
    year: 1977,
    pages: 447,
    genre: "Horror",
    genes: ["psychological", "isolated-setting", "dark", "gothic"],
    blurb: "A family caretakes an empty winter hotel that very much wants them to stay.",
  },
  {
    id: "rebecca",
    title: "Rebecca",
    author: "Daphne du Maurier",
    year: 1938,
    pages: 449,
    genre: "Thriller",
    genes: ["gothic", "unreliable-narrator", "mystery", "first-person", "dark"],
    blurb: "A new bride is haunted by the perfect, dead first wife she can never measure up to.",
  },
  {
    id: "gonegirl",
    title: "Gone Girl",
    author: "Gillian Flynn",
    year: 2012,
    pages: 432,
    genre: "Thriller",
    genes: ["unreliable-narrator", "plot-twist", "dark", "multiple-pov", "psychological"],
    blurb: "A wife vanishes on her anniversary and the husband's story stops adding up.",
  },
  {
    id: "dragontattoo",
    title: "The Girl with the Dragon Tattoo",
    author: "Stieg Larsson",
    year: 2005,
    pages: 465,
    genre: "Thriller",
    genes: ["mystery", "dark", "anti-hero", "plot-twist", "investigation"],
    blurb: "A disgraced journalist and a feral hacker reopen a decades-cold disappearance.",
  },
  {
    id: "silentpatient",
    title: "The Silent Patient",
    author: "Alex Michaelides",
    year: 2019,
    pages: 336,
    genre: "Thriller",
    genes: ["unreliable-narrator", "plot-twist", "psychological", "mystery", "fast-paced"],
    blurb: "A woman shoots her husband and never speaks again; a therapist needs to know why.",
  },
  {
    id: "attwn",
    title: "And Then There Were None",
    author: "Agatha Christie",
    year: 1939,
    pages: 272,
    genre: "Thriller",
    genes: ["mystery", "plot-twist", "isolated-setting", "dark", "ensemble"],
    blurb: "Ten strangers are lured to an island and killed off, one by one, by one of them.",
  },
  {
    id: "achilles",
    title: "The Song of Achilles",
    author: "Madeline Miller",
    year: 2011,
    pages: 416,
    genre: "Romance",
    genes: ["slow-burn-romance", "tragic", "historical", "mythology", "character-driven"],
    blurb: "The Iliad retold as a love story, from the boy who loved the greatest of the Greeks.",
  },
  {
    id: "outlander",
    title: "Outlander",
    author: "Diana Gabaldon",
    year: 1991,
    pages: 627,
    genre: "Romance",
    genes: ["slow-burn-romance", "historical", "time-travel", "epic-scope", "adventure"],
    blurb: "A WWII nurse touches a standing stone and wakes in the violent Scottish Highlands of 1743.",
  },
];

export const BOOK_GENOME: BookGenomeData = {
  genres: GENRE_COLORS,
  genes: GENE_MEANINGS,
  books: GENOME_BOOKS,
};
